name: DB Migration
on:
  workflow_dispatch:
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install SQLAlchemy + psycopg
        run: pip install sqlalchemy psycopg2-binary
      - name: Run migration
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python scripts/one_off_fix_add_p3_and_reset_stakes.py

