name: Run One-off DB Fix

on:
  workflow_dispatch: # run manually when needed

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install sqlalchemy psycopg[binary] psycopg2-binary

      - name: Run DB migration fix
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python scripts/one_off_fix_schema.py
