name: Run DB Migrations
on:
  workflow_dispatch:
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install sqlalchemy psycopg2-binary
      - name: Run migration
        run: python scripts/one_off_fix_add_p3_user.py
