name: Run DB Migration
on:
  workflow_dispatch:
jobs:
  migrate-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install sqlalchemy psycopg2-binary
      - name: Run migration script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python scripts/one_off_fix_wallet_timestamp.py
